# OLED_DRIVER_ENABLE = no   # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = no       # Enable keyboard RGB underglow
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = no
DEFERRED_EXEC_ENABLE = yes
LTO_ENABLE = yes           # Link Time Optimization (saves ~10-15%)
CONSOLE_ENABLE = no        # Disable console (saves ~400 bytes)
COMMAND_ENABLE = no        # Disable command feature (saves ~500 bytes)
SPACE_CADET_ENABLE = no    # Disable space cadet (saves ~350 bytes)
GRAVE_ESC_ENABLE = no      # Disable grave escape (saves ~50 bytes)
MAGIC_ENABLE = no          # Disable magic keycodes (saves ~100 bytes)
RGB_MATRIX_ENABLE = no
BOOTMAGIC_ENABLE = no      # ~200-400 bytes
MIDI_ENABLE = no           # ~100-200 bytes if enabled
UNICODE_ENABLE = no        # ~200+ bytes if enabled
AUTO_SHIFT_ENABLE = no     # ~300+ bytes if enabled
TAP_DANCE_ENABLE = no      # ~200+ bytes if enabled
COMBO_ENABLE = no          # ~150+ bytes if enabled
KEY_OVERRIDE_ENABLE = no   # ~100+ bytes if enabled
LEADER_ENABLE = no         # ~100+ bytes if enabled
